server:
  port: 8082
#sentinel模拟线程隔离
#  tomcat:
#    threads:
#      max: 25
#    accept-count: 25
#    max-connections: 100
spring:
  application:
    name: user-service
  profiles:
    active: dev
  config:
    import:
      - nacos:shared-log.yaml?group=DEFAULT_GROUP&refreshEnable=true
      - nacos:shared-jdbc.yaml?group=DEFAULT_GROUP
      - nacos:shared-openfeign.yaml?group=DEFAULT_GROUP
      - nacos:shared-seata.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: 123456
    sentinel:
      transport:
        dashboard: localhost:19090
      http-method-specify: true
aapo:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
